#############################################################################################
###              Stage where Docker is building spring boot app using maven               ###
#############################################################################################
FROM maven:3.8.3-openjdk-17 AS build

WORKDIR /app
COPY . .

RUN mvn clean package


#############################################################################################
### Stage where Docker is running a java process to run a service built in previous stage ###
#############################################################################################
FROM eclipse-temurin:17-jre-alpine

COPY --from=build /app/jag-jci-application-secure/target/jci-application-secure.jar ./jci-application-secure.jar

ENTRYPOINT ["java", "-Xmx2g", "-jar","/jci-application-secure.jar"]

#############################################################################################
 