# Deploy an artifact onto Test
name: TEMP Promote jag-jci-application and jag-jci-application-secure to Prod
on:
  workflow_dispatch:
    inputs:
      application:
        required: true
        description: What application you want to promote?
        type: choice
        options:
           - jag-jci-application
           - jag-jci-application-secure

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout ArgoCD Repo
        id: gitops
        uses: actions/checkout@v4
        with:
          repository: bcgov-c/tenant-gitops-52e74e
          ref: main
          token: ${{ secrets.ARGO_PAT }} # `GH_PAT` is a secret that contains your PAT
          path: gitops

      - name: Update ADMIN Helm Values and Commit
        id: helm-admin
        if: ${{ github.event.inputs.application == 'jag-jci-application' }}
        run: |
          # Clone the GitOps deployment configuration repository
          # Navigate to the directory containing your Helm values file for the environment develop -> DEV, test -> test and 
          cd gitops/charts

          # Update the Helm values file with the new image tag and version
          DATETIME=$(date +'%Y-%m-%d %H:%M:%S')  # Get current date and time

          sed -i "s/jcitag: .*/jcitag: prod # Image Updated on $DATETIME/" ../deploy/prod_values_jci.yaml
          sed -i "s/jciVersion: .*/jciVersion: v2.1 # Version Updated on $DATETIME/" ../deploy/prod_values_jci.yaml
          
          # Commit and push the changes
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          git add .
          
          git add ../deploy/prod_values_jci.yaml
          
          # Repackage Helm Chart      

          cd jci-gitops

          helm dependency build
          
          cd charts

          git add .
          
          git commit -m "Update Jag jci image tag"
          git push origin main  # Update the branch name as needed
      
      - name: Update API Helm Values and Commit
        id: helm-api
        if: ${{ github.event.inputs.application == 'jag-jci-application-secure' }}
        run: |
          # Clone the GitOps deployment configuration repository
          # Navigate to the directory containing your Helm values file for the environment develop -> DEV, test -> test and 
          cd gitops/charts

          # Update the Helm values file with the new image tag and version
          DATETIME=$(date +'%Y-%m-%d %H:%M:%S')  # Get current date and time

          sed -i "s/jcisecuretag: .*/jcisecuretag: prod # Image Updated on $DATETIME/" ../deploy/prod_values_jci.yaml
          sed -i "s/jcisecureVersion: .*/jcisecureVersion: v2.1 # Version Updated on $DATETIME/" ../deploy/prod_values_jci.yaml
          
          # Commit and push the changes
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          git add .
          
          git add ../deploy/prod_values_jci.yaml
          
          # Repackage Helm Chart      

          cd jci-gitops

          helm dependency build
          
          cd charts

          git add .
          
          git commit -m "Update Jag jci secure image tag"
          git push origin main  # Update the branch name as needed
